### ISSUE TITLE
microbe MASST 1.0

### ISSUE THREAD

**Issue by robinschmid** [mwang87/GNPS_MASST#25]
### TODO
- [ ] input controls from [fastsearch](https://fastlibrarysearch.ucsd.edu/)
- [ ] no need to select database
- [ ] input for min_matched_signals (spinner)
- [ ] USI or spectrum input (precursor m/z, charge, data points)
- [ ] how to run on spectrum - export mgf?
